# Generated by Django 6.0.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_demand_demandmaterial_machine_demandmachineorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='machine',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='quotation_items',
                to='ledger.machine'
            ),
        ),
    ]
