# Generated by Django 6.0.1
# 0006 depends on 0004 so it can run when 0005 is missing on server (e.g. older clone).
# It ensures Machine table exists before adding the FK.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_machine_table_if_missing(apps, schema_editor):
    """Create ledger_machine table if it does not exist (e.g. when 0005 was never applied)."""
    from django.db import connection
    with connection.cursor() as cursor:
        table = 'ledger_machine'
        if connection.vendor == 'postgresql':
            cursor.execute(
                "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = %s",
                [table]
            )
        elif connection.vendor == 'sqlite':
            cursor.execute(
                "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = %s",
                [table]
            )
        else:
            cursor.execute(
                "SELECT 1 FROM information_schema.tables WHERE table_name = %s",
                [table]
            )
        if cursor.fetchone():
            return
    Model = apps.get_model('ledger', 'Machine')
    schema_editor.create_model(Model)


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_inventoryitem_batch_tracking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add Machine to project state and create table if missing (no-op if 0005 already applied)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Machine',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('deleted', models.BooleanField(db_index=True, default=False)),
                        ('name', models.CharField(max_length=200, unique=True)),
                        ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                        ('description', models.TextField(blank=True, null=True)),
                        ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                        ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={'ordering': ['name']},
                ),
            ],
            database_operations=[
                migrations.RunPython(create_machine_table_if_missing, migrations.RunPython.noop),
            ],
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='machine',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='quotation_items',
                to='ledger.machine'
            ),
        ),
    ]
